// Lista completa de serviços disponíveis no AjudeX - 37 serviços em ordem alfabética
const SERVICES_LIST = [
  { id: 12, name: "Aulas de Inglês", icon: "🇺🇸", category: "Educação" },
  { id: 13, name: "Aulas de Matemática", icon: "🔢", category: "Educação" },
  { id: 14, name: "Aulas de Música", icon: "🎵", category: "Educação" },
  { id: 21, name: "Cabeleireiro", icon: "💇", category: "Beleza" },
  { id: 20, name: "Consultoria em TI", icon: "📱", category: "Digital" },
  { id: 31, name: "Consultoria Juridica", icon: "⚖️", category: "Outros" },
  { id: 27, name: "Costura", icon: "🪡", category: "Outros" },
  { id: 32, name: "Cuidador", icon: "🤗", category: "Outros" },
  { id: 9, name: "Culinária", icon: "👩‍🍳", category: "Alimentação" },
  { id: 33, name: "Depilação", icon: "✨", category: "Beleza" },
  { id: 17, name: "Design Gráfico", icon: "🎨", category: "Digital" },
  { id: 18, name: "Desenvolvimento Web", icon: "💻", category: "Digital" },
  { id: 10, name: "Doces e Bolos", icon: "🎂", category: "Alimentação" },
  { id: 19, name: "Edição de Vídeo", icon: "🎬", category: "Digital" },
  { id: 4, name: "Eletricista", icon: "⚡", category: "Casa" },
  { id: 3, name: "Encanamento", icon: "🔧", category: "Casa" },
  { id: 25, name: "Entrega", icon: "🚚", category: "Transporte" },
  { id: 29, name: "Fotografia", icon: "📸", category: "Outros" },
  { id: 2, name: "Jardinagem", icon: "🌱", category: "Casa" },
  { id: 1, name: "Limpeza", icon: "🧹", category: "Casa" },
  { id: 22, name: "Manicure", icon: "💅", category: "Beleza" },
  { id: 23, name: "Maquiagem", icon: "💄", category: "Beleza" },
  { id: 6, name: "Marcenaria", icon: "🪚", category: "Casa" },
  { id: 11, name: "Marmitas", icon: "🍱", category: "Alimentação" },
  { id: 36, name: "Massoterapia", icon: "💆", category: "Saúde" },
  { id: 26, name: "Motorista", icon: "🚗", category: "Transporte" },
  { id: 24, name: "Mudanças", icon: "📦", category: "Transporte" },
  { id: 7, name: "Pedreiro", icon: "🧱", category: "Casa" },
  { id: 30, name: "Personal Trainer", icon: "💪", category: "Outros" },
  { id: 28, name: "Pet Care", icon: "🐕", category: "Outros" },
  { id: 5, name: "Pintura", icon: "🎨", category: "Casa" },
  { id: 15, name: "Reforço Escolar", icon: "📚", category: "Educação" },
  { id: 37, name: "Reparo Carro&Moto", icon: "🔧", category: "Transporte" },
  { id: 34, name: "Sapateiro", icon: "👞", category: "Outros" },
  { id: 35, name: "Tattoo e Piercing", icon: "🔗", category: "Beleza" },
  { id: 16, name: "Tradução", icon: "🌐", category: "Educação" },
  { id: 8, name: "Vidraceiro", icon: "🪟", category: "Casa" },
];

module.exports = {
  SERVICES_LIST,
};
